-- MySQL Script generated by MySQL Workbench
-- Fri May  6 14:47:00 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MobileStore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MobileStore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MobileStore` DEFAULT CHARACTER SET utf8 ;
USE `MobileStore` ;

-- -----------------------------------------------------
-- Table `MobileStore`.`Addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MobileStore`.`Addresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `street` VARCHAR(100) NOT NULL,
  `building_number` INT NOT NULL,
  `corp` INT NULL,
  `entrance` INT NULL,
  `apt` INT NULL,
  `floor` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MobileStore`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MobileStore`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `account_type` ENUM("admin", "user") NOT NULL,
  `birth` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `MobileStore`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MobileStore`.`Customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `phone_number` BIGINT(12) NOT NULL,
  `id_address_c` INT NULL,
  `email` VARCHAR(100) NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_address_idx` (`id_address_c` ASC) VISIBLE,
  INDEX `id_user_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `id_address_c`
    FOREIGN KEY (`id_address_c`)
    REFERENCES `MobileStore`.`Addresses` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `MobileStore`.`Users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MobileStore`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MobileStore`.`Categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `MobileStore`.`Screens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MobileStore`.`Screens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name_technology` VARCHAR(45) NOT NULL,
  `size` FLOAT NOT NULL,
  `resolution` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MobileStore`.`Manufacturers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MobileStore`.`Manufacturers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `id_address_m` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_address_idx` (`id_address_m` ASC) VISIBLE,
  CONSTRAINT `id_address_m`
    FOREIGN KEY (`id_address_m`)
    REFERENCES `MobileStore`.`Addresses` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MobileStore`.`Descriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MobileStore`.`Descriptions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(45) NOT NULL,
  `model` VARCHAR(100) NOT NULL,
  `year` INT NOT NULL,
  `operating_system` VARCHAR(45) NOT NULL,
  `id_screen` INT NULL,
  `CPU` VARCHAR(100) NOT NULL,
  `RAM` INT NOT NULL,
  `memory` INT NOT NULL,
  `camera` VARCHAR(100) NOT NULL,
  `battery` VARCHAR(45) NOT NULL,
  `id_manufacturer` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_screen_idx` (`id_screen` ASC) VISIBLE,
  INDEX `id_manufacturer_idx` (`id_manufacturer` ASC) VISIBLE,
  CONSTRAINT `id_screen`
    FOREIGN KEY (`id_screen`)
    REFERENCES `MobileStore`.`Screens` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `id_manufacturer`
    FOREIGN KEY (`id_manufacturer`)
    REFERENCES `MobileStore`.`Manufacturers` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MobileStore`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MobileStore`.`Products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_category` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `price` FLOAT NOT NULL,
  `id_description` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_category_idx` (`id_category` ASC) VISIBLE,
  INDEX `id_description_idx` (`id_description` ASC) VISIBLE,
  CONSTRAINT `id_category`
    FOREIGN KEY (`id_category`)
    REFERENCES `MobileStore`.`Categories` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `id_description`
    FOREIGN KEY (`id_description`)
    REFERENCES `MobileStore`.`Descriptions` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MobileStore`.`Payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MobileStore`.`Payments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MobileStore`.`Deliveries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MobileStore`.`Deliveries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `days` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MobileStore`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MobileStore`.`Orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_customer` INT NOT NULL,
  `id_product` INT NOT NULL,
  `count` INT NOT NULL,
  `order_amount` FLOAT NOT NULL,
  `id_delivery` INT NULL,
  `id_payment` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_customer_idx` (`id_customer` ASC) VISIBLE,
  INDEX `id_product_idx` (`id_product` ASC) VISIBLE,
  INDEX `id_payment_idx` (`id_payment` ASC) VISIBLE,
  INDEX `id_delivery_idx` (`id_delivery` ASC) VISIBLE,
  CONSTRAINT `id_customer`
    FOREIGN KEY (`id_customer`)
    REFERENCES `MobileStore`.`Customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `id_product`
    FOREIGN KEY (`id_product`)
    REFERENCES `MobileStore`.`Products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `id_payment`
    FOREIGN KEY (`id_payment`)
    REFERENCES `MobileStore`.`Payments` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `id_delivery`
    FOREIGN KEY (`id_delivery`)
    REFERENCES `MobileStore`.`Deliveries` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MobileStore`.`Stores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MobileStore`.`Stores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `id_address_s` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_address_idx` (`id_address_s` ASC) VISIBLE,
  CONSTRAINT `id_address_s`
    FOREIGN KEY (`id_address_s`)
    REFERENCES `MobileStore`.`Addresses` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MobileStore`.`Suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MobileStore`.`Suppliers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `id_address_sup` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_address_idx` (`id_address_sup` ASC) VISIBLE,
  CONSTRAINT `id_address_sup`
    FOREIGN KEY (`id_address_sup`)
    REFERENCES `MobileStore`.`Addresses` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MobileStore`.`Warehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MobileStore`.`Warehouse` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_product_w` INT NOT NULL,
  `quantity` INT NOT NULL,
  `id_store` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_product_idx` (`id_product_w` ASC) VISIBLE,
  INDEX `id_store_idx` (`id_store` ASC) VISIBLE,
  CONSTRAINT `id_product_w`
    FOREIGN KEY (`id_product_w`)
    REFERENCES `MobileStore`.`Products` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_store`
    FOREIGN KEY (`id_store`)
    REFERENCES `MobileStore`.`Stores` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MobileStore`.`Warehouse_Suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MobileStore`.`Warehouse_Suppliers` (
  `id_warehouse` INT NOT NULL,
  `id_supplier` INT NOT NULL,
  PRIMARY KEY (`id_warehouse`, `id_supplier`),
  INDEX `fk_Warehouse_has_Suppliers_Suppliers1_idx` (`id_supplier` ASC) VISIBLE,
  CONSTRAINT `fk_Warehouse_has_Suppliers_Warehouse1`
    FOREIGN KEY (`id_warehouse`)
    REFERENCES `MobileStore`.`Warehouse` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Warehouse_has_Suppliers_Suppliers1`
    FOREIGN KEY (`id_supplier`)
    REFERENCES `MobileStore`.`Suppliers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
